spring:
  application:
    name: e-commerce-application-gateway
  cloud:
    gateway:
      routes:
        ## USER SERVICE
        - id: e-commerce-service
          uri: lb://e-commerce-service
          predicates:
            - Path=/e-commerce-service/**
          filters:
            - StripPrefix=1
        ## FUND TRANSFER SERVICE
        - id: fund-transfer-service
          uri: lb://fund-transfer-service
          predicates:
            - Path=/fund-transfer/**
          filters:
            - StripPrefix=1


server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka