spring:
  application:
    name: e-commerce-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/product_orders
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    format:
      date: dd-M-yyyy hh:mm a

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}
